import sys
from functools import wraps
from loguru import logger

from pyv8.flag import *


class AttributeJSConfig:
    def __init__(
            self,
            name,
            get_cb,
            set_cb=None,
            v8_property_attribute=3,  # v8::PropertyAttribute
            location=2,  # FlagLocation
            receiver_check=1,
            cross_origin_check_for_get=1,  # FlagReceiverCheck
            cross_origin_check_for_set=1,  # FlagCrossOriginCheck
            v8_side_effect=2,  # FlagCrossOriginCheck
    ):
        self.name = name
        self.get_cb = get_cb
        self.set_cb = set_cb
        self.v8_property_attribute = v8_property_attribute
        self.location = location
        self.receiver_check = receiver_check
        self.cross_origin_check_for_get = cross_origin_check_for_get
        self.cross_origin_check_for_set = cross_origin_check_for_set
        self.v8_side_effect = v8_side_effect

    def __call__(self, func):
        setattr(func, "__v8_method__", 1)
        setattr(func, "__v8_location", self.location)
        setattr(func, "__v8_receiver_check", self.receiver_check)
        setattr(func, "__v8_cross_origin_check_for_get", self.cross_origin_check_for_get)
        setattr(func, "__v8_cross_origin_check_for_set", self.cross_origin_check_for_set)
        setattr(func, "__v8_v8_side_effect", self.v8_side_effect)


class AttributeConfig:
    def __init__(
            self,
            v8_property_attribute=V8Attribute.kNone,  # v8::PropertyAttribute
            location=FlagLocation.kPrototype,  # FlagLocation
            receiver_check=FlagReceiverCheck.kCheck,
            cross_origin_check_for_get=FlagCrossOriginCheck.kCheck,  # FlagReceiverCheck
            cross_origin_check_for_set=FlagCrossOriginCheck.kCheck,  # FlagCrossOriginCheck
            side_effect=SideEffectType.kHasSideEffect,  # FlagCrossOriginCheck
    ):
        self.property_attribute = v8_property_attribute
        self.location = location
        self.receiver_check = receiver_check
        self.cross_origin_check_for_get = cross_origin_check_for_get
        self.cross_origin_check_for_set = cross_origin_check_for_set
        self.side_effect = side_effect

    def __call__(self, func):
        setattr(func, "__v8_method__", 1)
        setattr(func, "__v8_property_attribute", self.property_attribute)
        setattr(func, "__v8_location", self.location)
        setattr(func, "__v8_receiver_check", self.receiver_check)
        setattr(func, "__v8_cross_origin_check_for_get", self.cross_origin_check_for_get)
        setattr(func, "__v8_cross_origin_check_for_set", self.cross_origin_check_for_set)
        setattr(func, "__v8_side_effect", self.side_effect)
        return func

    def __str__(self):
        return f'attr_{self.location}{self.property_attribute}{self.receiver_check}{self.cross_origin_check_for_get}{self.cross_origin_check_for_set}{self.side_effect}'


class OperationConfig:
    def __init__(
            self,
            length=0,
            v8_property_attribute=V8Attribute.kNone,
            location=FlagLocation.kPrototype,
            receiver_check=FlagReceiverCheck.kCheck,
            cross_origin_check=FlagCrossOriginCheck.kCheck,
            side_effect=SideEffectType.kHasSideEffect,
    ):
        self.length = length
        self.property_attribute = v8_property_attribute
        self.location = location
        self.receiver_check = receiver_check
        self.cross_origin_check = cross_origin_check
        self.side_effect = side_effect

    def __call__(self, func):
        setattr(func, "__v8_method", 1)
        setattr(func, "__v8_length", self.length)
        setattr(func, "__v8_property_attribute", self.property_attribute)
        setattr(func, "__v8_location", self.location)
        setattr(func, "__v8_receiver_check", self.receiver_check)
        setattr(func, "__v8_cross_origin_check", self.cross_origin_check)
        setattr(func, "__v8_side_effect", self.side_effect)
        return func

    def __str__(self):
        return f'operation_{self.location}{self.length}{self.property_attribute}{self.receiver_check}{self.cross_origin_check}{self.side_effect}'


__hook_exclude_name = (
    "dir", "dirxml", "profile", "profileEnd", "clear", "table", "keys", "values",
    "debug", "undebug", "inspect", "copy", "queryObjects", 'monitor', 'unmonitor',
    "$", "$$", "$_", "$0", "$1", "$2", "$3", "$4", "$", "$x", "DataVie",
    "String", "Array", "Date", "Object", "window", "Symbol", "Number", "Function",
    "Symbol.toPrimitive", "Symbol.toStringTag",
    "parseFloat", "parseInt", "Math", "BigInt", "RegExp", "console", "isNaN", "Boolean",
    "faker",  "unescape", "NaN", "Infinity", "_cf_chl_opt", "decodeURIComponent"
)


def __v8_get_hook__(self, name, value=None, error=None, ctx_type=''):
    if name in __hook_exclude_name:
        return
    if isinstance(name, str) and name.startswith('a1_0x'):
        return
    msg = f"{ctx_type} getter: {self.__class__.__name__}.{name} -> {value}"
    if error:
        msg += f", error: {error}"
    logger.info(msg)


def __v8_set_hook__(self, name, value, error, ctx_type=''):
    if isinstance(name, str) and name.startswith('a1_0x'):
        return
    msg = f"{ctx_type} setter: {self.__class__.__name__}.{name} = {value}"
    if error:
        msg += f", error: {error}"
    logger.info(msg)


def __v8_method_hook__(self, func_name, arguments, value, has_error, ctx_type=''):
    msg = f"{ctx_type} method: {self.__name__ if isinstance(self, type) else self.__class__.__name__}.{func_name}{tuple(arguments)}"
    if has_error:
        msg += f" -> error: {value}"
    else:
        msg += f" -> {value}"
    logger.info(msg)


def __v8_construct_hook__(name, arguments, value, has_error, is_construct_call, ctx_type=''):
    if is_construct_call:
        msg = f"{ctx_type} construct: new {name}{tuple(arguments)} -> {value}"
    else:
        msg = f"{ctx_type} construct: {name}{tuple(arguments)} -> {value}"
    if has_error:
        msg += f", has_error: {has_error}"
    logger.info(msg)


exposed_constructs = {}
exposed_names = [
    "Option",
    "Image",
    "Audio",
    "webkitURL",
    "webkitRTCPeerConnection",
    "webkitMediaStream",
    "WebKitMutationObserver",
    "WebKitCSSMatrix",
    "XSLTProcessor",
    "XPathResult",
    "XPathExpression",
    "XPathEvaluator",
    "XMLSerializer",
    "XMLHttpRequestUpload",
    "XMLHttpRequestEventTarget",
    "XMLHttpRequest",
    "XMLDocument",
    "WritableStreamDefaultWriter",
    "WritableStreamDefaultController",
    "WritableStream",
    "Worker",
    "WindowControlsOverlayGeometryChangeEvent",
    "WindowControlsOverlay",
    "Window",
    "WheelEvent",
    "WebSocket",
    "WebGLVertexArrayObject",
    "WebGLUniformLocation",
    "WebGLTransformFeedback",
    "WebGLTexture",
    "WebGLSync",
    "WebGLShaderPrecisionFormat",
    "WebGLShader",
    "WebGLSampler",
    "WebGLRenderingContext",
    "WebGLRenderbuffer",
    "WebGLQuery",
    "WebGLProgram",
    "WebGLObject",
    "WebGLFramebuffer",
    "WebGLContextEvent",
    "WebGLBuffer",
    "WebGLActiveInfo",
    "WebGL2RenderingContext",
    "WaveShaperNode",
    "VisualViewport",
    "VisibilityStateEntry",
    "VirtualKeyboardGeometryChangeEvent",
    "ViewTransition",
    "VideoPlaybackQuality",
    "VideoFrame",
    "VideoColorSpace",
    "ValidityState",
    "VTTCue",
    "UserActivation",
    "URLSearchParams",
    "URLPattern",
    "URL",
    "UIEvent",
    "TrustedTypePolicyFactory",
    "TrustedTypePolicy",
    "TrustedScriptURL",
    "TrustedScript",
    "TrustedHTML",
    "TreeWalker",
    "TransitionEvent",
    "TransformStreamDefaultController",
    "TransformStream",
    "TrackEvent",
    "TouchList",
    "TouchEvent",
    "Touch",
    "ToggleEvent",
    "TimeRanges",
    "TextUpdateEvent",
    "TextTrackList",
    "TextTrackCueList",
    "TextTrackCue",
    "TextTrack",
    "TextMetrics",
    "TextFormatUpdateEvent",
    "TextFormat",
    "TextEvent",
    "TextEncoderStream",
    "TextEncoder",
    "TextDecoderStream",
    "TextDecoder",
    "Text",
    "TaskSignal",
    "TaskPriorityChangeEvent",
    "TaskController",
    "TaskAttributionTiming",
    "SyncManager",
    "SubmitEvent",
    "StyleSheetList",
    "StyleSheet",
    "StylePropertyMapReadOnly",
    "StylePropertyMap",
    "StorageEvent",
    "Storage",
    "StereoPannerNode",
    "StaticRange",
    "SourceBufferList",
    "SourceBuffer",
    "ShadowRoot",
    "Selection",
    "SecurityPolicyViolationEvent",
    "ScriptProcessorNode",
    "ScreenOrientation",
    "Screen",
    "Scheduling",
    "Scheduler",
    "SVGViewElement",
    "SVGUseElement",
    "SVGUnitTypes",
    "SVGTransformList",
    "SVGTransform",
    "SVGTitleElement",
    "SVGTextPositioningElement",
    "SVGTextPathElement",
    "SVGTextElement",
    "SVGTextContentElement",
    "SVGTSpanElement",
    "SVGSymbolElement",
    "SVGSwitchElement",
    "SVGStyleElement",
    "SVGStringList",
    "SVGStopElement",
    "SVGSetElement",
    "SVGScriptElement",
    "SVGSVGElement",
    "SVGRectElement",
    "SVGRect",
    "SVGRadialGradientElement",
    "SVGPreserveAspectRatio",
    "SVGPolylineElement",
    "SVGPolygonElement",
    "SVGPointList",
    "SVGPoint",
    "SVGPatternElement",
    "SVGPathElement",
    "SVGNumberList",
    "SVGNumber",
    "SVGMetadataElement",
    "SVGMatrix",
    "SVGMaskElement",
    "SVGMarkerElement",
    "SVGMPathElement",
    "SVGLinearGradientElement",
    "SVGLineElement",
    "SVGLengthList",
    "SVGLength",
    "SVGImageElement",
    "SVGGraphicsElement",
    "SVGGradientElement",
    "SVGGeometryElement",
    "SVGGElement",
    "SVGForeignObjectElement",
    "SVGFilterElement",
    "SVGFETurbulenceElement",
    "SVGFETileElement",
    "SVGFESpotLightElement",
    "SVGFESpecularLightingElement",
    "SVGFEPointLightElement",
    "SVGFEOffsetElement",
    "SVGFEMorphologyElement",
    "SVGFEMergeNodeElement",
    "SVGFEMergeElement",
    "SVGFEImageElement",
    "SVGFEGaussianBlurElement",
    "SVGFEFuncRElement",
    "SVGFEFuncGElement",
    "SVGFEFuncBElement",
    "SVGFEFuncAElement",
    "SVGFEFloodElement",
    "SVGFEDropShadowElement",
    "SVGFEDistantLightElement",
    "SVGFEDisplacementMapElement",
    "SVGFEDiffuseLightingElement",
    "SVGFEConvolveMatrixElement",
    "SVGFECompositeElement",
    "SVGFEComponentTransferElement",
    "SVGFEColorMatrixElement",
    "SVGFEBlendElement",
    "SVGEllipseElement",
    "SVGElement",
    "SVGDescElement",
    "SVGDefsElement",
    "SVGComponentTransferFunctionElement",
    "SVGClipPathElement",
    "SVGCircleElement",
    "SVGAnimationElement",
    "SVGAnimatedTransformList",
    "SVGAnimatedString",
    "SVGAnimatedRect",
    "SVGAnimatedPreserveAspectRatio",
    "SVGAnimatedNumberList",
    "SVGAnimatedNumber",
    "SVGAnimatedLengthList",
    "SVGAnimatedLength",
    "SVGAnimatedInteger",
    "SVGAnimatedEnumeration",
    "SVGAnimatedBoolean",
    "SVGAnimatedAngle",
    "SVGAnimateTransformElement",
    "SVGAnimateMotionElement",
    "SVGAnimateElement",
    "SVGAngle",
    "SVGAElement",
    "Response",
    "ResizeObserverSize",
    "ResizeObserverEntry",
    "ResizeObserver",
    "Request",
    "ReportingObserver",
    "ReadableStreamDefaultReader",
    "ReadableStreamDefaultController",
    "ReadableStreamBYOBRequest",
    "ReadableStreamBYOBReader",
    "ReadableStream",
    "ReadableByteStreamController",
    "Range",
    "RadioNodeList",
    "RTCTrackEvent",
    "RTCStatsReport",
    "RTCSessionDescription",
    "RTCSctpTransport",
    "RTCRtpTransceiver",
    "RTCRtpSender",
    "RTCRtpReceiver",
    "RTCPeerConnectionIceEvent",
    "RTCPeerConnectionIceErrorEvent",
    "RTCPeerConnection",
    "RTCIceTransport",
    "RTCIceCandidate",
    "RTCErrorEvent",
    "RTCError",
    "RTCEncodedVideoFrame",
    "RTCEncodedAudioFrame",
    "RTCDtlsTransport",
    "RTCDataChannelEvent",
    "RTCDTMFToneChangeEvent",
    "RTCDTMFSender",
    "RTCCertificate",
    "PromiseRejectionEvent",
    "ProgressEvent",
    "Profiler",
    "ProcessingInstruction",
    "PopStateEvent",
    "PointerEvent",
    "PluginArray",
    "Plugin",
    "PictureInPictureWindow",
    "PictureInPictureEvent",
    "PeriodicWave",
    "PerformanceTiming",
    "PerformanceServerTiming",
    "PerformanceResourceTiming",
    "PerformancePaintTiming",
    "PerformanceObserverEntryList",
    "PerformanceObserver",
    "PerformanceNavigationTiming",
    "PerformanceNavigation",
    "PerformanceMeasure",
    "PerformanceMark",
    "PerformanceLongTaskTiming",
    "PerformanceEventTiming",
    "PerformanceEntry",
    "PerformanceElementTiming",
    "Performance",
    "Path2D",
    "PannerNode",
    "PageTransitionEvent",
    "OverconstrainedError",
    "OscillatorNode",
    "OffscreenCanvasRenderingContext2D",
    "OffscreenCanvas",
    "OfflineAudioContext",
    "OfflineAudioCompletionEvent",
    "NodeList",
    "NodeIterator",
    "NodeFilter",
    "Node",
    "NetworkInformation",
    "NavigatorUAData",
    "Navigator",
    "NavigationTransition",
    "NavigationHistoryEntry",
    "NavigationDestination",
    "NavigationCurrentEntryChangeEvent",
    "Navigation",
    "NavigateEvent",
    "NamedNodeMap",
    "MutationRecord",
    "MutationObserver",
    "MouseEvent",
    "MimeTypeArray",
    "MimeType",
    "MessagePort",
    "MessageEvent",
    "MessageChannel",
    "MediaStreamTrackVideoStats",
    "MediaStreamTrackProcessor",
    "MediaStreamTrackGenerator",
    "MediaStreamTrackEvent",
    "MediaStreamTrackAudioStats",
    "MediaStreamTrack",
    "MediaStreamEvent",
    "MediaStreamAudioSourceNode",
    "MediaStreamAudioDestinationNode",
    "MediaStream",
    "MediaSourceHandle",
    "MediaSource",
    "MediaRecorder",
    "MediaQueryListEvent",
    "MediaQueryList",
    "MediaList",
    "MediaError",
    "MediaEncryptedEvent",
    "MediaElementAudioSourceNode",
    "MediaCapabilities",
    "MathMLElement",
    "Location",
    "LayoutShiftAttribution",
    "LayoutShift",
    "LargestContentfulPaint",
    "KeyframeEffect",
    "KeyboardEvent",
    "IntersectionObserverEntry",
    "IntersectionObserver",
    "InputEvent",
    "InputDeviceInfo",
    "InputDeviceCapabilities",
    "Ink",
    "ImageData",
    "ImageCapture",
    "ImageBitmapRenderingContext",
    "ImageBitmap",
    "IdleDeadline",
    "IIRFilterNode",
    "IDBVersionChangeEvent",
    "IDBTransaction",
    "IDBRequest",
    "IDBOpenDBRequest",
    "IDBObjectStore",
    "IDBKeyRange",
    "IDBIndex",
    "IDBFactory",
    "IDBDatabase",
    "IDBCursorWithValue",
    "IDBCursor",
    "History",
    "HighlightRegistry",
    "Highlight",
    "Headers",
    "HashChangeEvent",
    "HTMLVideoElement",
    "HTMLUnknownElement",
    "HTMLUListElement",
    "HTMLTrackElement",
    "HTMLTitleElement",
    "HTMLTimeElement",
    "HTMLTextAreaElement",
    "HTMLTemplateElement",
    "HTMLTableSectionElement",
    "HTMLTableRowElement",
    "HTMLTableElement",
    "HTMLTableColElement",
    "HTMLTableCellElement",
    "HTMLTableCaptionElement",
    "HTMLStyleElement",
    "HTMLSpanElement",
    "HTMLSourceElement",
    "HTMLSlotElement",
    "HTMLSelectElement",
    "HTMLScriptElement",
    "HTMLQuoteElement",
    "HTMLProgressElement",
    "HTMLPreElement",
    "HTMLPictureElement",
    "HTMLParamElement",
    "HTMLParagraphElement",
    "HTMLOutputElement",
    "HTMLOptionsCollection",
    "HTMLOptionElement",
    "HTMLOptGroupElement",
    "HTMLObjectElement",
    "HTMLOListElement",
    "HTMLModElement",
    "HTMLMeterElement",
    "HTMLMetaElement",
    "HTMLMenuElement",
    "HTMLMediaElement",
    "HTMLMarqueeElement",
    "HTMLMapElement",
    "HTMLLinkElement",
    "HTMLLegendElement",
    "HTMLLabelElement",
    "HTMLLIElement",
    "HTMLInputElement",
    "HTMLImageElement",
    "HTMLIFrameElement",
    "HTMLHtmlElement",
    "HTMLHeadingElement",
    "HTMLHeadElement",
    "HTMLHRElement",
    "HTMLFrameSetElement",
    "HTMLFrameElement",
    "HTMLFormElement",
    "HTMLFormControlsCollection",
    "HTMLFontElement",
    "HTMLFieldSetElement",
    "HTMLEmbedElement",
    "HTMLElement",
    "HTMLDocument",
    "HTMLDivElement",
    "HTMLDirectoryElement",
    "HTMLDialogElement",
    "HTMLDetailsElement",
    "HTMLDataListElement",
    "HTMLDataElement",
    "HTMLDListElement",
    "HTMLCollection",
    "HTMLCanvasElement",
    "HTMLButtonElement",
    "HTMLBodyElement",
    "HTMLBaseElement",
    "HTMLBRElement",
    "HTMLAudioElement",
    "HTMLAreaElement",
    "HTMLAnchorElement",
    "HTMLAllCollection",
    "GeolocationPositionError",
    "GeolocationPosition",
    "GeolocationCoordinates",
    "Geolocation",
    "GamepadHapticActuator",
    "GamepadEvent",
    "GamepadButton",
    "Gamepad",
    "GainNode",
    "FormDataEvent",
    "FormData",
    "FontFaceSetLoadEvent",
    "FontFace",
    "FocusEvent",
    "FileReader",
    "FileList",
    "File",
    "FeaturePolicy",
    "External",
    "EventTarget",
    "EventSource",
    "EventCounts",
    "Event",
    "ErrorEvent",
    "EncodedVideoChunk",
    "EncodedAudioChunk",
    "ElementInternals",
    "Element",
    "EditContext",
    "DynamicsCompressorNode",
    "DragEvent",
    "DocumentType",
    "DocumentTimeline",
    "DocumentFragment",
    "Document",
    "DelegatedInkTrailPresenter",
    "DelayNode",
    "DecompressionStream",
    "DataTransferItemList",
    "DataTransferItem",
    "DataTransfer",
    "DOMTokenList",
    "DOMStringMap",
    "DOMStringList",
    "DOMRectReadOnly",
    "DOMRectList",
    "DOMRect",
    "DOMQuad",
    "DOMPointReadOnly",
    "DOMPoint",
    "DOMParser",
    "DOMMatrixReadOnly",
    "DOMMatrix",
    "DOMImplementation",
    "DOMException",
    "DOMError",
    "CustomStateSet",
    "CustomEvent",
    "CustomElementRegistry",
    "Crypto",
    "CountQueuingStrategy",
    "ConvolverNode",
    "ContentVisibilityAutoStateChangeEvent",
    "ConstantSourceNode",
    "CompressionStream",
    "CompositionEvent",
    "Comment",
    "CloseWatcher",
    "CloseEvent",
    "ClipboardEvent",
    "CharacterData",
    "CharacterBoundsUpdateEvent",
    "ChannelSplitterNode",
    "ChannelMergerNode",
    "CanvasRenderingContext2D",
    "CanvasPattern",
    "CanvasGradient",
    "CanvasCaptureMediaStreamTrack",
    "CSSVariableReferenceValue",
    "CSSUnparsedValue",
    "CSSUnitValue",
    "CSSTranslate",
    "CSSTransition",
    "CSSTransformValue",
    "CSSTransformComponent",
    "CSSSupportsRule",
    "CSSStyleValue",
    "CSSStyleSheet",
    "CSSStyleRule",
    "CSSStyleDeclaration",
    "CSSStartingStyleRule",
    "CSSSkewY",
    "CSSSkewX",
    "CSSSkew",
    "CSSScopeRule",
    "CSSScale",
    "CSSRuleList",
    "CSSRule",
    "CSSRotate",
    "CSSPropertyRule",
    "CSSPositionValue",
    "CSSPositionTryRule",
    "CSSPositionTryDescriptors",
    "CSSPerspective",
    "CSSPageRule",
    "CSSNumericValue",
    "CSSNumericArray",
    "CSSNamespaceRule",
    "CSSMediaRule",
    "CSSMatrixComponent",
    "CSSMathValue",
    "CSSMathSum",
    "CSSMathProduct",
    "CSSMathNegate",
    "CSSMathMin",
    "CSSMathMax",
    "CSSMathInvert",
    "CSSMathClamp",
    "CSSLayerStatementRule",
    "CSSLayerBlockRule",
    "CSSKeywordValue",
    "CSSKeyframesRule",
    "CSSKeyframeRule",
    "CSSImportRule",
    "CSSImageValue",
    "CSSGroupingRule",
    "CSSFontPaletteValuesRule",
    "CSSFontFaceRule",
    "CSSCounterStyleRule",
    "CSSContainerRule",
    "CSSConditionRule",
    "CSSAnimation",
    "CSS",
    "CDATASection",
    "ByteLengthQueuingStrategy",
    "BrowserCaptureMediaStreamTrack",
    "BroadcastChannel",
    "BlobEvent",
    "Blob",
    "BiquadFilterNode",
    "BeforeUnloadEvent",
    "BeforeInstallPromptEvent",
    "BaseAudioContext",
    "BarProp",
    "AudioWorkletNode",
    "AudioSinkInfo",
    "AudioScheduledSourceNode",
    "AudioProcessingEvent",
    "AudioParamMap",
    "AudioParam",
    "AudioNode",
    "AudioListener",
    "AudioDestinationNode",
    "AudioData",
    "AudioContext",
    "AudioBufferSourceNode",
    "AudioBuffer",
    "Attr",
    "AnimationTimeline",
    "AnimationPlaybackEvent",
    "AnimationEvent",
    "AnimationEffect",
    "Animation",
    "AnalyserNode",
    "AbstractRange",
    "AbortSignal",
    "AbortController",
    "AbsoluteOrientationSensor",
    "Accelerometer",
    "AudioDecoder",
    "AudioEncoder",
    "AudioWorklet",
    "BatteryManager",
    "Cache",
    "CacheStorage",
    "Clipboard",
    "ClipboardItem",
    "CookieChangeEvent",
    "CookieStore",
    "CookieStoreManager",
    "Credential",
    "CredentialsContainer",
    "CryptoKey",
    "DeviceMotionEvent",
    "DeviceMotionEventAcceleration",
    "DeviceMotionEventRotationRate",
    "DeviceOrientationEvent",
    "FederatedCredential",
    "GPU",
    "GPUAdapter",
    "GPUAdapterInfo",
    "GPUBindGroup",
    "GPUBindGroupLayout",
    "GPUBuffer",
    "GPUBufferUsage",
    "GPUCanvasContext",
    "GPUColorWrite",
    "GPUCommandBuffer",
    "GPUCommandEncoder",
    "GPUCompilationInfo",
    "GPUCompilationMessage",
    "GPUComputePassEncoder",
    "GPUComputePipeline",
    "GPUDevice",
    "GPUDeviceLostInfo",
    "GPUError",
    "GPUExternalTexture",
    "GPUInternalError",
    "GPUMapMode",
    "GPUOutOfMemoryError",
    "GPUPipelineError",
    "GPUPipelineLayout",
    "GPUQuerySet",
    "GPUQueue",
    "GPURenderBundle",
    "GPURenderBundleEncoder",
    "GPURenderPassEncoder",
    "GPURenderPipeline",
    "GPUSampler",
    "GPUShaderModule",
    "GPUShaderStage",
    "GPUSupportedFeatures",
    "GPUSupportedLimits",
    "GPUTexture",
    "GPUTextureUsage",
    "GPUTextureView",
    "GPUUncapturedErrorEvent",
    "GPUValidationError",
    "GravitySensor",
    "Gyroscope",
    "IdleDetector",
    "ImageDecoder",
    "ImageTrack",
    "ImageTrackList",
    "Keyboard",
    "KeyboardLayoutMap",
    "LinearAccelerationSensor",
    "Lock",
    "LockManager",
    "MIDIAccess",
    "MIDIConnectionEvent",
    "MIDIInput",
    "MIDIInputMap",
    "MIDIMessageEvent",
    "MIDIOutput",
    "MIDIOutputMap",
    "MIDIPort",
    "MediaDeviceInfo",
    "MediaDevices",
    "MediaKeyMessageEvent",
    "MediaKeySession",
    "MediaKeyStatusMap",
    "MediaKeySystemAccess",
    "MediaKeys",
    "NavigationPreloadManager",
    "NavigatorManagedData",
    "OrientationSensor",
    "PasswordCredential",
    "RelativeOrientationSensor",
    "ScreenDetailed",
    "ScreenDetails",
    "Sensor",
    "SensorErrorEvent",
    "ServiceWorker",
    "ServiceWorkerContainer",
    "ServiceWorkerRegistration",
    "StorageManager",
    "SubtleCrypto",
    "VideoDecoder",
    "VideoEncoder",
    "VirtualKeyboard",
    "WGSLLanguageFeatures",
    "WebTransport",
    "WebTransportBidirectionalStream",
    "WebTransportDatagramDuplexStream",
    "WebTransportError",
    "Worklet",
    "XRDOMOverlayState",
    "XRLayer",
    "XRWebGLBinding",
    "AuthenticatorAssertionResponse",
    "AuthenticatorAttestationResponse",
    "AuthenticatorResponse",
    "PublicKeyCredential",
    "Bluetooth",
    "BluetoothCharacteristicProperties",
    "BluetoothDevice",
    "BluetoothRemoteGATTCharacteristic",
    "BluetoothRemoteGATTDescriptor",
    "BluetoothRemoteGATTServer",
    "BluetoothRemoteGATTService",
    "CaptureController",
    "DocumentPictureInPicture",
    "EyeDropper",
    "FileSystemDirectoryHandle",
    "FileSystemFileHandle",
    "FileSystemHandle",
    "FileSystemWritableFileStream",
    "FontData",
    "FragmentDirective",
    "HID",
    "HIDConnectionEvent",
    "HIDDevice",
    "HIDInputReportEvent",
    "IdentityCredential",
    "IdentityProvider",
    "IdentityCredentialError",
    "LaunchParams",
    "LaunchQueue",
    "NavigatorLogin",
    "NotRestoredReasonDetails",
    "NotRestoredReasons",
    "OTPCredential",
    "PaymentAddress",
    "PaymentRequest",
    "PaymentRequestUpdateEvent",
    "PaymentResponse",
    "PaymentManager",
    "PaymentMethodChangeEvent",
    "Presentation",
    "PresentationAvailability",
    "PresentationConnection",
    "PresentationConnectionAvailableEvent",
    "PresentationConnectionCloseEvent",
    "PresentationConnectionList",
    "PresentationReceiver",
    "PresentationRequest",
    "PressureObserver",
    "PressureRecord",
    "ProtectedAudience",
    "Serial",
    "SerialPort",
    "StorageBucket",
    "StorageBucketManager",
    "USB",
    "USBAlternateInterface",
    "USBConfiguration",
    "USBConnectionEvent",
    "USBDevice",
    "USBEndpoint",
    "USBInTransferResult",
    "USBInterface",
    "USBIsochronousInTransferPacket",
    "USBIsochronousInTransferResult",
    "USBIsochronousOutTransferPacket",
    "USBIsochronousOutTransferResult",
    "USBOutTransferResult",
    "WakeLock",
    "WakeLockSentinel",
    "XRAnchor",
    "XRAnchorSet",
    "XRBoundedReferenceSpace",
    "XRCPUDepthInformation",
    "XRCamera",
    "XRDepthInformation",
    "XRFrame",
    "XRHitTestResult",
    "XRHitTestSource",
    "XRInputSource",
    "XRInputSourceArray",
    "XRInputSourceEvent",
    "XRInputSourcesChangeEvent",
    "XRLightEstimate",
    "XRLightProbe",
    "XRPose",
    "XRRay",
    "XRReferenceSpace",
    "XRReferenceSpaceEvent",
    "XRRenderState",
    "XRRigidTransform",
    "XRSession",
    "XRSessionEvent",
    "XRSpace",
    "XRSystem",
    "XRTransientInputHitTestResult",
    "XRTransientInputHitTestSource",
    "XRView",
    "XRViewerPose",
    "XRViewport",
    "XRWebGLDepthInformation",
    "XRWebGLLayer",
    "BackgroundFetchManager",
    "BackgroundFetchRecord",
    "BackgroundFetchRegistration",
    "BluetoothUUID",
    "CSSNestedDeclarations",
    "CSSViewTransitionRule",
    "CaretPosition",
    "ChapterInformation",
    "CropTarget",
    "DocumentPictureInPictureEvent",
    "Fence",
    "FencedFrameConfig",
    "HTMLFencedFrameElement",
    "MediaMetadata",
    "MediaSession",
    "NavigationActivation",
    "Notification",
    "PageRevealEvent",
    "PageSwapEvent",
    "PerformanceLongAnimationFrameTiming",
    "PerformanceScriptTiming",
    "PeriodicSyncManager",
    "PermissionStatus",
    "Permissions",
    "PushManager",
    "PushSubscription",
    "PushSubscriptionOptions",
    "RTCDataChannel",
    "RemotePlayback",
    "ScrollTimeline",
    "ViewTimeline",
    "SharedStorage",
    "SharedStorageWorklet",
    "SharedWorker",
    "SnapEvent",
    "SpeechSynthesis",
    "SpeechSynthesisErrorEvent",
    "SpeechSynthesisEvent",
    "SpeechSynthesisUtterance",
    "SpeechSynthesisVoice",
    "ViewTransitionTypeSet",
    "WebSocketError",
    "WebSocketStream",
]


class ConstructorConfig:
    def __init__(
            self,
            exposed=FlagExposed.kYes,
            constructor=FlagConstructor.kDontAll,
            length=0,
            v8_array=0,  # FlagArrayProto
            immutable=0,
            has_constructor=1,
            hook=True,
    ):
        self.exposed = exposed
        self.constructor = constructor
        self.length = length
        self.hook = hook
        self.v8_array = v8_array
        self.immutable = immutable
        self.has_constructor = has_constructor

    def __call__(self, cls):
        if self.exposed == FlagExposed.kYes:
            exposed_constructs[cls.__name__] = cls
        setattr(cls, "__v8_constructor__", self.constructor)
        setattr(cls, "__v8_length__", self.length)
        setattr(cls, "__v8_array__", self.v8_array)
        setattr(cls, "__v8_immutable__", self.immutable)
        setattr(cls, "__v8_has_constructor__", self.has_constructor)
        if self.hook:
            cls.__v8_get_hook__ = __v8_get_hook__
            cls.__v8_set_hook__ = __v8_set_hook__
            cls.__v8_method_hook__ = __v8_method_hook__
            cls.__v8_construct_hook__ = __v8_construct_hook__
        return cls

    def __str__(self):
        return f'construct_{self.exposed}{self.constructor}{self.length}{int(self.v8_array)}{int(self.immutable)}{int(self.has_constructor)}'


def impl_warp(cls):
    father = cls.__base__
    for name in cls.__dict__:
        if name == '__module__':
            continue
        setattr(father, name, cls.__dict__[name])
    return father


def attr_warp(**attrs):
    def decorator(func):
        @wraps(func)
        def wrapper(*args, **kwargs):
            return func(*args, **kwargs)
        for name, value in attrs.items():
            setattr(wrapper, name, value)
        return wrapper
    return decorator


class CtxTypeIndex:
    count = 0

    @classmethod
    def get(cls):
        cls.count += 1
        return cls.count
